[package]
name = "rust_image_filter"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image"] }
image = "0.25.2"
native-dialog = "0.7.0"
rand = "0.8.5"
log = "0.4"
env_logger = "0.11.5"
